### ISSUE TITLE
Add Support for Windows Build 20348

### ISSUE THREAD

**Issue by DreadsCasey** [deadjakk/patch-checker#3]
I noticed your app only supports up to build 19042. I have a Windows server 2022 that needs it's patching assessed and this app fit the use case perfectly, unfortunately it didn't support the build 20348 so I'm tentative to report the results from patchchecker using build 19042.

**Comment by deadjakk** [comment]
Added support for the additional builds. Keep in mind you may want to add additional CVEs to cves.txt file to have them populate on the result page. I added the last one on the line in cves.txt just to have something for it to populate. The other CVEs in the cves.txt file are too old for that build to have ever been affected therefore those will not appear.

If any that you find are priv esc vulns with public PoCs, please make a pull request so they can be added :+1:
